[ClassVersion("1.0.0"), FriendlyName("rsClientMofs")]
class RS_rsClientMofs : OMI_BaseResource
{
    [key] string Name;
    [write,ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] string Ensure;
    [write] boolean Logging
};